version: '3.8'

services:
  chatwoot: &chatwoot
    image: ${CHATWOOT_IMAGE}
    environment: 
      - SECRET_KEY_BASE
      - FRONTEND_URL
      - ENABLE_ACCOUNT_SIGNUP=false
      - MAILER_SENDER_EMAIL
      - REDIS_URL=redis://redis
      - REDIS_PASSWORD
      - POSTGRES_HOST=postgres
      - POSTGRES_USERNAME
      - POSTGRES_DB
      - POSTGRES_PASSWORD   
      - RAILS_ENV=production
      - RAILS_MAX_THREADS=5
      - NODE_ENV=production
      - INSTALLATION_ENV=docker
      - ACTIVE_STORAGE_SERVICE=local
      - LOG_LEVEL=warn
    ports:
      - 80:3000
    volumes:
      - app_data:/app/storage

    depends_on:
      - postgres
      - redis

    entrypoint: docker/entrypoints/rails.sh
    command: ['bundle', 'exec', 'rails', 's', '-p', '3000', '-b', '0.0.0.0']

  sidekiq:
    <<: *chatwoot
    depends_on:
      - postgres
      - redis
    command: ['bundle', 'exec', 'sidekiq', '-C', 'config/sidekiq.yml']

  postgres:
    image: postgres:14.4
    environment:
      - POSTGRES_HOST
      - POSTGRES_USERNAME
      - POSTGRES_DB
      - POSTGRES_PASSWORD
    volumes:
      - pg_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    command: ["sh", "-c", "redis-server --requirepass \"${REDIS_PASSWORD}\""]
    volumes:
      - redis_data:/data
  
volumes:
  app_data:
  pg_data:
  redis_data:
    

